# Generated by Django 4.2.4 on 2023-08-26 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"verbose_name_plural": "data"},
        ),
    ]
