# Generated by Django 4.2.4 on 2023-09-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_data_added_alter_data_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="insight",
            field=models.CharField(db_column="insight", max_length=200),
        ),
        migrations.AlterField(
            model_name="data",
            name="title",
            field=models.CharField(db_column="title", max_length=200),
        ),
        migrations.AlterField(
            model_name="data",
            name="url",
            field=models.CharField(db_column="url", max_length=200),
        ),
    ]
