# Generated by Django 4.2.4 on 2023-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_data_insight_alter_data_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="source",
            field=models.CharField(db_column="source", max_length=200),
        ),
    ]
